INSERT INTO breeds (breed, id_person) VALUES ('Siamese', 1);
INSERT INTO breeds (breed, id_person) VALUES ('British Shorthair', 2);
INSERT INTO breeds (breed, id_person) VALUES ('Abyssinian Cat', 3);
INSERT INTO breeds (breed, id_person) VALUES ('American Bobtail Cat Breed', 4);
INSERT INTO breeds (breed, id_person) VALUES ('American Curl Cat Breed', 5);
INSERT INTO breeds (breed, id_person) VALUES ('Bombay Cat', 6);
INSERT INTO breeds (breed, id_person) VALUES ('Chartreux Cat Breed', 7);
INSERT INTO breeds (breed, id_person) VALUES ('British Shorthair Cat Breed', 8);
INSERT INTO breeds (breed, id_person) VALUES ('Maine Coon', 9);
INSERT INTO breeds (breed, id_person) VALUES ('Persian cat', 10);
INSERT INTO breeds (breed, id_person) VALUES ('Ragdoll', 11);
INSERT INTO breeds (breed, id_person) VALUES ('Sphynx cat', 12);
INSERT INTO breeds (breed, id_person) VALUES ('Abyssinian Cat breed', 13);
INSERT INTO breeds (breed, id_person) VALUES ('Exotic Shorthair', 14);
INSERT INTO breeds (breed, id_person) VALUES ('Scottish Fold', 15);
INSERT INTO breeds (breed, id_person) VALUES ('Burmese cat', 16);
INSERT INTO breeds (breed, id_person) VALUES ('Birman', 17);
INSERT INTO breeds (breed, id_person) VALUES ('Bombay', 18);
INSERT INTO breeds (breed, id_person) VALUES ('Russian Blue', 19);
INSERT INTO breeds (breed, id_person) VALUES ('Siberian cat', 20);
INSERT INTO breeds (breed, id_person) VALUES ('Norwegian Forest cat', 21);
INSERT INTO breeds (breed, id_person) VALUES ('American Curl', 22);
INSERT INTO breeds (breed, id_person) VALUES ('American Bobtail', 23);
INSERT INTO breeds (breed, id_person) VALUES ('Balinese cat', 24);
INSERT INTO breeds (breed, id_person) VALUES ('Oriental Shorthair', 25);
INSERT INTO breeds (breed, id_person) VALUES ('Chartreux', 26);
INSERT INTO breeds (breed, id_person) VALUES ('Turkish Angora', 27);
INSERT INTO breeds (breed, id_person) VALUES ('Japanese Bobtail', 28);
INSERT INTO breeds (breed, id_person) VALUES ('American Wirehair', 29);
INSERT INTO breeds (breed, id_person) VALUES ('Somali cat', 30);
INSERT INTO breeds (breed, id_person) VALUES ('Himalayan cat', 31);