CREATE DATABASE formula_01;
USE formula_01;

-- APENAS PARA REALIZAR A PRATICA DE PRIMARY KEY E FOREIGN KEY
ALTER TABLE piloto 
ADD CONSTRAINT fk_construtores FOREIGN KEY (i_construtores) REFERENCES construtores (id);

-- TIVE QUE DELETAR O BANCO DE DADOS
DROP DATABASE formula_1;

-- TIVE QUE DELETAR A TABELA E CRIAR NOVAMENTE
DROP TABLE piloto;

-- SECAO CRIANDO TABELAS

CREATE TABLE IF NOT EXISTS construtores(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS piloto(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    age INT NOT NULL,
    nacionalidade VARCHAR(50) NOT NULL,
    i_construtores INT 
);

CREATE TABLE IF NOT EXISTS chefe_de_equipe(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    age INT NOT NULL,
    nacionalidade VARCHAR(50) NOT NULL,
    construtores VARCHAR(50)
    -- FOREIGN KEY (construtores) REFERENCES construtores(nome)
);

CREATE TABLE IF NOT EXISTS grand_prix(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS circuit(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(400) NOT NULL
);

CREATE TABLE IF NOT EXISTS race_date(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    race_day VARCHAR(200) NOT NULL,
    grand_prix VARCHAR(400)
    -- FOREIGN KEY (grand_prix) REFERENCES grand_prix(name)
);

CREATE TABLE IF NOT EXISTS pontos(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    points INT NOT NULL,
    piloto VARCHAR(50)
    -- FOREIGN KEY (piloto) REFERENCES piloto(name)
);
