-- QUESTÃO 03: FILTRO QUE MOSTRE SOMENTE OS NOMES
SELECT Nome FROM pessoas;

-- QUESTÃO 04: FILTRO QUE MOSTRE SOMENTE OS CPF
SELECT CPF FROM pessoas;

-- QUESTÃO 05: FILTRO QUE MOSTRE SOMENTE OS ANO
SELECT ANO FROM pessoas;

-- QUESTÃO 06: FILTRO QUE MOSTRE SOMENTE OS MES
SELECT MES FROM pessoas;

SELECT * FROM pessoas;