-- QUESTAO 07: FILTRO QUE MOSTRE SOMENTE INDIVIDUOS DE NOMES IGUAIS
SELECT DISTINCT Nome FROM pessoas;

-- QUESTAO 08: ESCOLHA UMA COLUNA E ALTERE O SEU NOME
SELECT Nome, Cpf as 'CPF', Ano, Mes as 'Mês' FROM pessoas;

SELECT * FROM pessoas;